# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator(code='invalid_password', message='password shall be 8-20 characters, include a number and a special character', regex='^(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$')])),
                ('apikey', models.CharField(blank=True, max_length=128, null=True)),
                ('date_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.CharField(choices=[('0', 'Notdelete'), ('1', 'Delete')], default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(max_length=100)),
                ('subscription', models.CharField(blank=True, choices=[('0', 'OFF'), ('1', 'ON')], default='0', max_length=1, null=True)),
                ('membership', models.CharField(blank=True, choices=[('0', 'Default'), ('1', 'Bronze'), ('2', 'Silver'), ('3', 'Gold'), ('4', 'Platinum')], default='0', max_length=1, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('office_number', models.CharField(blank=True, max_length=20, null=True)),
                ('office_number_isd', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('mobile_number_isd', models.CharField(max_length=20)),
                ('date_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('companytype', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('preferred_language', models.CharField(blank=True, default='0', max_length=3, null=True)),
                ('priceformat', models.CharField(blank=True, default='1', max_length=2, null=True)),
                ('timeformat', models.CharField(blank=True, default='1', max_length=2, null=True)),
                ('dateformat', models.CharField(blank=True, default='1', max_length=2, null=True)),
                ('preffered_currency', models.CharField(blank=True, default='1', max_length=2, null=True)),
                ('username', models.CharField(max_length=100)),
                ('customuserid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app1.User')),
            ],
        ),
    ]
